// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservaCanchita.Data;

#nullable disable

namespace ReservaCanchita.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250825121903_Configuracion")]
    partial class Configuracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ReservaCanchita.Models.Cancha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NombreCancha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Canchas");
                });

            modelBuilder.Entity("ReservaCanchita.Models.CanchaSemana", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Activo")
                        .HasColumnType("int");

                    b.Property<int>("CanchaId")
                        .HasColumnType("int");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.ToTable("CanchasSemanas");
                });

            modelBuilder.Entity("ReservaCanchita.Models.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorNumerico")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ValorString")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Configuraciones");
                });

            modelBuilder.Entity("ReservaCanchita.Models.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CuentaTipoId")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("ReservaCanchita.Models.HorarioBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CanchaId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.ToTable("HorariosBase");
                });

            modelBuilder.Entity("ReservaCanchita.Models.HorarioDisponible", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CanchaId")
                        .HasColumnType("int");

                    b.Property<bool>("EstaReservado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.ToTable("HorariosDisponibles");
                });

            modelBuilder.Entity("ReservaCanchita.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HorarioDisponibleId")
                        .HasColumnType("int");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HorarioDisponibleId")
                        .IsUnique();

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("ReservaCanchita.Models.CanchaSemana", b =>
                {
                    b.HasOne("ReservaCanchita.Models.Cancha", "Cancha")
                        .WithMany("CanchasSemanas")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");
                });

            modelBuilder.Entity("ReservaCanchita.Models.HorarioBase", b =>
                {
                    b.HasOne("ReservaCanchita.Models.Cancha", "Cancha")
                        .WithMany("HorariosBase")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");
                });

            modelBuilder.Entity("ReservaCanchita.Models.HorarioDisponible", b =>
                {
                    b.HasOne("ReservaCanchita.Models.Cancha", "Cancha")
                        .WithMany("HorariosDisponibles")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");
                });

            modelBuilder.Entity("ReservaCanchita.Models.Reserva", b =>
                {
                    b.HasOne("ReservaCanchita.Models.HorarioDisponible", "HorarioDisponible")
                        .WithOne("Reserva")
                        .HasForeignKey("ReservaCanchita.Models.Reserva", "HorarioDisponibleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HorarioDisponible");
                });

            modelBuilder.Entity("ReservaCanchita.Models.Cancha", b =>
                {
                    b.Navigation("CanchasSemanas");

                    b.Navigation("HorariosBase");

                    b.Navigation("HorariosDisponibles");
                });

            modelBuilder.Entity("ReservaCanchita.Models.HorarioDisponible", b =>
                {
                    b.Navigation("Reserva");
                });
#pragma warning restore 612, 618
        }
    }
}
